CREATE TABLE EMPLOYEE(
	EMP_ID INT NOT NULL PRIMARY KEY,
	EMP_NAME VARCHAR(20),
	SALARY INT,
	EMP_DEPT VARCHAR(20));
CREATE TABLE MANAGER(
	MGR_NAME VARCHAR(20),
	EMP_ID INT NOT NULL PRIMARY KEY,
	MGR_ID INT,
	FOREIGN KEY (EMP_ID) REFERENCES 
	EMPLOYEE(EMP_ID) ON DELETE CASCADE);
CREATE TABLE TIMESHEET(
	EMP_ID INT,
	DATE DATETIME,
	ACTIVITY VARCHAR(20),
	HOURS INT,
	STATUS VARCHAR(20),
	FOREIGN KEY (EMP_ID) REFERENCES 
	EMPLOYEE(EMP_ID) ON DELETE CASCADE);


SELECT *
FROM EMPLOYEE